apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: provider-aws-amp-providerconfig-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: provider-aws-amp-providerconfig-access
subjects:
  - kind: ServiceAccount
    name: provider-aws-amp-9082de79614f
    namespace: container-platform
